//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DBEntities : DbContext
{
    public DBEntities()
        : base("name=DBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Club> Clubs { get; set; }
    public virtual DbSet<ClubMember> ClubMembers { get; set; }
    public virtual DbSet<Employee> Employees { get; set; }
    public virtual DbSet<MeetingRoomBookingRecord> MeetingRoomBookingRecords { get; set; }
    public virtual DbSet<WorkShiftRecord> WorkShiftRecords { get; set; }
    public virtual DbSet<WorkShiftRecordsDepIdView> WorkShiftRecordsDepIdViews { get; set; }
    public virtual DbSet<Board> Boards { get; set; }
    public virtual DbSet<ClockInOutRecord> ClockInOutRecords { get; set; }
    public virtual DbSet<Leave> Leaves { get; set; }
    public virtual DbSet<PayrollCalculation> PayrollCalculations { get; set; }
    public virtual DbSet<Performance> Performances { get; set; }
    public virtual DbSet<SpecialPlan> SpecialPlans { get; set; }
    public virtual DbSet<TomOrder> TomOrders { get; set; }
    public virtual DbSet<WorkMessage> WorkMessages { get; set; }
}
